### PR TITLE
treat coverage files as phony to allow easy rerunning

### PR DESCRIPTION
**Pull request by caeost**
# Summary

Mark these files as phony so that `make testcover` can be run repeatedly.

# Checklist
- [ ] Did you add or remove any calls to a service or frontend?
    - [ ] Update the API dependency inventory
- [ ] Is this a backend service?
    - [ ] Did you add any new endpoints or change the contract/signature of an endpoint?
    	- [ ] Have you updated the OpenAPI specs for this service?
    	- [ ] Have you updated Spring contracts for this service?
    - [ ] Did you add any new database migrations?
    	- [ ] Do you need to add indexes?
	    - [ ] Have the migrations been tested?
- [ ] If this is a frontend application, can you still run the application locally using the provided script/command?
- [ ] Is this a client library, do you need to update the consumer contract tests?
- [ ] Are there any failing automated checks, and if so, have you left an explanation for reviewers?

### CODE REVIEW

**Comment by glewis-ANet** [comment]
I feel like this is an attempt to circumvent how make works since we're basically saying that these aren't real files when they are.  It also makes it different from other targets that create files (like `build`).  I think you can achieve what you want by running `make clean testcover`.  Is there a problem with doing that other than being a little longer to type?

**Comment by caeost** [comment]
> I feel like this is an attempt to circumvent how make works since we're basically saying that these aren't real files when they are. It also makes it different from other targets that create files (like `build`). I think you can achieve what you want by running `make clean testcover`. Is there a problem with doing that other than being a little longer to type?

Well I guess I would need to remember to always do that and to take the cost of cleaning everything but yeah I guess maybe we shouldn't do this. Maybe we need to actually take the test files as dependencies to the recipes so that make does figure it out right.

**Review by glewis-ANet — APPROVED** [review]
This looks good since it will allow the test target to be redone anytime you change the test files

**Review by xanderflood — COMMENTED** [review]
It looks like we're only including _test files now, which suggests that tests would not be re-run if you make a change to a non-test file? I'm not super familiar with Make so maybe that's not the effect, but if that's the behavior here, I don't think that's right.

Personally, I don't agree that the original approach (phony) was bad or a misuse of the concept. Make assumes files are built deterministically, and not all files are in fact built deterministically. Test output (like coverage files) are an example of a file where Make's basic assumptions aren't really valid, and I think using PHONY is a reasonably way to communicate that.

**Comment by caeost** [comment]
> It looks like we're only including _test files now, which suggests that tests would not be re-run if you make a change to a non-test file? I'm not super familiar with Make so maybe that's not the effect, but if that's the behavior here, I don't think that's right.
> 
> Personally, I don't agree that the original approach (phony) was bad or a misuse of the concept. Make assumes files are built deterministically, and not all files are in fact built deterministically. Test output (like coverage files) are an example of a file where Make's basic assumptions aren't really valid, and I think using PHONY is a reasonably way to communicate that.

Yeah I agree that this is imperfect, I was thinking about what to do about that whether it should depend on build but apparently we also just have a search already defined for all go files so I have switched used that.

The coverage files should be deterministic in theory but we've long discussed that make doesn't entirely make sense for testing, although producing a coverage files is maybe one of the ways it does to me.

**Pull request merged**
